name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main  # Ganti jadi 'master' kalau branch utama kamu bernama master

jobs:
  web-deploy:
    name: Sync Files to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/
          exclude: |
            **/.git*
            **/.github*
            **/.git*/**
            README.md